<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['user_id' => '1',
            'course_id' => '1',
            'role_id' => '2', 
            'email' => 'bsa@email.com', 
            'password' => Hash::make('bsa@email.com'),
            'student_number' => '2018-00001-TG-O', 
            'first_name' => 'Jon Jeremiah',
            'middle_name' => 'Malakas',
            'last_name' => 'Bartolome',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456700',
            'address' => 'Bulacan, Malolos',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
             ['user_id' => '2',
            'course_id' => '2',
            'role_id' => '2', 
            'email' => 'ece@email.com', 
            'password' => Hash::make('ece@email.com'),
            'student_number' => '2018-00002-TG-O', 
            'first_name' => 'Bryan',
            'middle_name' => 'Santiago',
            'last_name' => 'Laserna',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456701',
            'address' => 'Purok 13 South Daang Hari, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
             ['user_id' => '3',
            'course_id' => '3',
            'role_id' => '2', 
            'email' => 'bsme@email.com', 
            'password' => Hash::make('bsme@email.com'),
            'student_number' => '2018-00003-TG-O', 
            'first_name' => 'Earl',
            'middle_name' => 'Vincent',
            'last_name' => 'Caroliner',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456702',
            'address' => 'Lower Bicutan, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
             ['user_id' => '4',
            'course_id' => '4',
            'role_id' => '2', 
            'email' => 'bshr@email.com', 
            'password' => Hash::make('bshr@email.com'),
            'student_number' => '2018-00004-TG-O', 
            'first_name' => 'Hajji',
            'middle_name' => 'Janloui',
            'last_name' => 'Luciano',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456703',
            'address' => 'Bambang, Sta Ana Signal, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
             ['user_id' => '5',
            'course_id' => '5',
            'role_id' => '2', 
            'email' => 'bsmm@email.com', 
            'password' => Hash::make('bsmm@email.com'),
            'student_number' => '2018-00005-TG-O', 
            'first_name' => 'Jojemar',
            'middle_name' => 'Mar',
            'last_name' => 'Exala',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456704',
            'address' => 'Makati City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
             ['user_id' => '6',
            'course_id' => '6',
            'role_id' => '2', 
            'email' => 'bsoa@email.com', 
            'password' => Hash::make('bsoa@email.com'),
            'student_number' => '2018-00006-TG-O', 
            'first_name' => 'Russel',
            'middle_name' => 'Apurada',
            'last_name' => 'Claveria',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456705',
            'address' => 'Western, Bicutan, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
             ['user_id' => '7',
            'course_id' => '7',
            'role_id' => '2', 
            'email' => 'bsede@email.com', 
            'password' => Hash::make('bsede@email.com'),
            'student_number' => '2018-00007-TG-O', 
            'first_name' => 'Roe Bien',
            'middle_name' => 'Astra',
            'last_name' => 'Arnaiz',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456706',
            'address' => 'Lower Bicutan, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
            ['user_id' => '8',
            'course_id' => '8',
            'role_id' => '2', 
            'email' => 'bsedm@email.com', 
            'password' => Hash::make('bsedm@email.com'),
            'student_number' => '2018-00008-TG-O', 
            'first_name' => 'Juan',
            'middle_name' => 'Carlos',
            'last_name' => 'Amaguin',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456707',
            'address' => 'Paranaque City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
            ['user_id' => '9',
            'course_id' => '9',
            'role_id' => '2', 
            'email' => 'bsit@email.com', 
            'password' => Hash::make('bsit@email.com'),
            'student_number' => '2018-00009-TG-O', 
            'first_name' => 'Sebastian',
            'middle_name' => 'Carlo',
            'last_name' => 'Cabiades',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456708',
            'address' => 'Alabang, Muntinlupa City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,
        ],
            ['user_id' => '10',
            'course_id' => '10',
            'role_id' => '2', 
            'email' => 'domt@email.com', 
            'password' => Hash::make('domt@email.com'),
            'student_number' => '2018-00010-TG-O', 
            'first_name' => 'Timothy',
            'middle_name' => 'Swift',
            'last_name' => 'Beldeniza',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456709',
            'address' => 'Lower Bicutan, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0, 
        ],
            ['user_id' => '11',
            'course_id' => '11',
            'role_id' => '2', 
            'email' => 'dict@email.com', 
            'password' => Hash::make('dict@email.com'),
            'student_number' => '2018-00011-TG-O', 
            'first_name' => 'John Andrew',
            'middle_name' => 'P',
            'last_name' => 'Mahipos',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456710',
            'address' => 'Lower Bicutan, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,       
        ],
            ['user_id' => '12',
            'course_id' => '1',
            'role_id' => '2', 
            'email' => 'bsa-member@email.com', 
            'password' => Hash::make('bsa-member@email.com'),
            'student_number' => '2018-00012-TG-O', 
            'first_name' => 'BSA John',
            'middle_name' => 'Fitzgerald',
            'last_name' => 'Kennedy',
            'gender' => '1',
            'date_of_birth' => '2000-01-01',
            'mobile_number' => '+639123456710',
            'address' => 'Lower Bicutan, Taguig City',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
            'status' => 0,       
        ],
        ];

        DB::table('users')->insert($data);
    }
}